remove BaseFindFilterValidator
LT-Students/DigitalOffice-Kernel pull request #121
Opened 2023-04-05 07:14 UTC by a5x55555

https://trello.com/c/RlseeCRj/215-kernel-remove-basefindfiltervalidator

2023-04-06 11:48 UTC, SolovyovDmitry requested changes
You should upgrade the version of the library

2023-04-10 12:21 UTC, SolovyovDmitry approved these changes

2023-04-18 11:57 UTC, VLiamin approved these changes

2023-04-21 12:54 UTC, VLiamin approved these changes

2023-04-21 15:25 UTC, merged