Add UserId parameter to AccessValidator
LT-Students/DigitalOffice-Kernel pull request #21
Opened 2021-04-14 22:37 UTC by KostinP

2021-04-15 11:15 UTC, 24eeeee approved these changes

2021-04-15 11:51 UTC, MariyaSin approved these changes

2021-04-15 11:57 UTC, TIove approved these changes

2021-04-15 12:32 UTC, DarkFelas commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +        public bool HasRights(Guid? userId, params int[] rightIds)
not good. plz add new method HasRights

2021-04-15 12:33 UTC, DarkFelas requested changes
check comment

2021-04-15 12:38 UTC, borovHokage approved these changes

2021-04-15 12:41 UTC, DarkFelas requested changes

2021-04-15 12:41 UTC, DarkFelas commented on LT.DigitalOffice.Kernel.nuspec
> +    <version>1.1.23</version>
we already have published 1.1.22?

2021-04-15 13:33 UTC, KostinP commented on LT.DigitalOffice.Kernel.nuspec
> +    <version>1.1.23</version>
Fixed.

2021-04-15 13:34 UTC, KostinP commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +        public bool HasRights(Guid? userId, params int[] rightIds)
Fixed good?

2021-04-16 03:58 UTC, DarkFelas commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +        public bool HasRights(Guid? userId, params int[] rightIds)
what for this method?

2021-04-16 04:00 UTC, DarkFelas requested changes

2021-04-16 04:00 UTC, DarkFelas commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +            if (userId == null)
if (!userId.HasValue)
{
 userId = _httpContext.GetUserId();
}

2021-04-16 04:00 UTC, DarkFelas commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +            else
remove

2021-04-16 04:00 UTC, DarkFelas commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +                ICheckUserIsAdminRequest.CreateObj((Guid)userId),
userId.Value

2021-04-16 04:00 UTC, DarkFelas commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +                ICheckUserRightsRequest.CreateObj((Guid)userId, rightIds),
userId.Value

2021-04-16 04:00 UTC, DarkFelas commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +            else
remove

2021-04-16 04:00 UTC, DarkFelas commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +            if (userId == null)
if (!userId.HasValue)

2021-04-16 04:00 UTC, DarkFelas commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +        private bool CheckUserRights(Guid? userId, int[] rightIds)
why private?

2021-04-16 11:23 UTC, KostinP commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +        private bool CheckUserRights(Guid? userId, int[] rightIds)
Fixed.

2021-04-16 11:23 UTC, KostinP commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +            if (userId == null)
Fixed.

2021-04-16 11:24 UTC, KostinP commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +            else
Fixed.

2021-04-16 11:24 UTC, KostinP commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +                ICheckUserRightsRequest.CreateObj((Guid)userId, rightIds),
Fixed.

2021-04-16 11:24 UTC, KostinP commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +                ICheckUserIsAdminRequest.CreateObj((Guid)userId),
Fixed.

2021-04-16 11:24 UTC, KostinP commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +            else
Fixed.

2021-04-16 11:24 UTC, KostinP commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +            if (userId == null)
Fixed.

2021-04-16 11:24 UTC, KostinP commented on src/Kernel/AccessValidatorEngine/AccessValidator.cs
> +        public bool HasRights(Guid? userId, params int[] rightIds)
Fixed.

2021-04-16 11:31 UTC, DarkFelas approved these changes

2021-04-16 11:34 UTC, merged