add companiesCache
LT-Students/DigitalOffice-Kernel pull request #59
Opened 2021-11-24 19:04 UTC by Cheephot

2021-11-24 22:15 UTC, VladSpitsin requested changes

2021-11-24 22:15 UTC, VladSpitsin commented on src/Kernel.RedisSupport/Kernel.RedisSupport.csproj
>      <PropertyGroup>
fix tabs

2021-11-25 15:01 UTC, MariyaSin approved these changes

2021-11-25 15:26 UTC, VladSpitsin approved these changes

2021-11-25 15:31 UTC, grinakate approved these changes

2021-11-25 15:31 UTC, actimellka approved these changes

2021-11-25 16:53 UTC, ndoriomedov approved these changes

2021-11-25 16:57 UTC, merged